trigger:
  branches:
    include:
      - master

pr:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo Running tests...
    displayName: 'Run Tests'

  # 在這裡添加您的測試步驟，例如運行測試腳本或測試框架

  - script: echo Tests passed! Pulling code to AP server...
    displayName: 'Pull Code to AP Server'

  - script: |
      ssh richard@192.168.158.133 'cd C:\xampp\htdocs\test && git pull origin master'
    displayName: 'Execute Pull Command on AP Server'